
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardIconData : Luban.BeanBase
{
    public CardIconData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsString) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["path"].IsString) { throw new SerializationException(); }  Path = _buf["path"]; }
    }

    public static CardIconData DeserializeCardIconData(JSONNode _buf)
    {
        return new CardIconData(_buf);
    }

    /// <summary>
    /// 图标id
    /// </summary>
    public readonly string Id;
    /// <summary>
    /// 图标位置
    /// </summary>
    public readonly string Path;
   
    public const int __ID__ = -110305517;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "path:" + Path + ","
        + "}";
    }
}

}
