
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CardData : Luban.BeanBase
{
    public CardData(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (card.Etype)_buf["type"].AsInt; }
        { if(!_buf["ownership"].IsNumber) { throw new SerializationException(); }  Ownership = (card.Eownership)_buf["ownership"].AsInt; }
        { if(!_buf["defaultCombinationCount"].IsNumber) { throw new SerializationException(); }  DefaultCombinationCount = _buf["defaultCombinationCount"]; }
        { if(!_buf["durationTime"].IsNumber) { throw new SerializationException(); }  DurationTime = _buf["durationTime"]; }
        { if(!_buf["iconUrl"].IsString) { throw new SerializationException(); }  IconUrl = _buf["iconUrl"]; }
        { if(!_buf["bStacked"].IsBoolean) { throw new SerializationException(); }  BStacked = _buf["bStacked"]; }
    }

    public static CardData DeserializeCardData(JSONNode _buf)
    {
        return new CardData(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字(自动生成)
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 卡牌类型(自动获取)
    /// </summary>
    public readonly card.Etype Type;
    /// <summary>
    /// 卡牌归属(自动获取)
    /// </summary>
    public readonly card.Eownership Ownership;
    /// <summary>
    /// 默认可合成次数(自动获取)
    /// </summary>
    public readonly int DefaultCombinationCount;
    /// <summary>
    /// 存在时间
    /// </summary>
    public readonly int DurationTime;
    /// <summary>
    /// 卡牌图标地址(自动获取)
    /// </summary>
    public readonly string IconUrl;
    /// <summary>
    /// 是否可堆叠(自动获取)
    /// </summary>
    public readonly bool BStacked;
   
    public const int __ID__ = 55917306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "type:" + Type + ","
        + "ownership:" + Ownership + ","
        + "defaultCombinationCount:" + DefaultCombinationCount + ","
        + "durationTime:" + DurationTime + ","
        + "iconUrl:" + IconUrl + ","
        + "bStacked:" + BStacked + ","
        + "}";
    }
}

}
