
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.card
{
public partial class TbIcon
{
    private readonly System.Collections.Generic.Dictionary<string, CardIconData> _dataMap;
    private readonly System.Collections.Generic.List<CardIconData> _dataList;
    
    public TbIcon(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, CardIconData>();
        _dataList = new System.Collections.Generic.List<CardIconData>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            CardIconData _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = CardIconData.DeserializeCardIconData(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<string, CardIconData> DataMap => _dataMap;
    public System.Collections.Generic.List<CardIconData> DataList => _dataList;

    public CardIconData GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public CardIconData Get(string key) => _dataMap[key];
    public CardIconData this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

