
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.card
{ 
    public enum Etype
    {
        /// <summary>
        /// 特殊卡牌
        /// </summary>
        SPECIAL = 1,
        /// <summary>
        /// 普通卡牌
        /// </summary>
        NORMAL = 2,
        /// <summary>
        /// 资源卡牌
        /// </summary>
        RESOURCE = 3,
        /// <summary>
        /// 动物卡牌
        /// </summary>
        ANIMAL = 4,
        /// <summary>
        /// 特效卡牌（包含增益和减益）
        /// </summary>
        BUFF = 5,
    }

} 

