
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.card
{ 
    public enum Eownership
    {
        /// <summary>
        /// 基础设施
        /// </summary>
        BASE = 1,
        /// <summary>
        /// 环境
        /// </summary>
        ENVIRONMENT = 2,
        /// <summary>
        /// 生态
        /// </summary>
        ECOLOGY = 3,
        /// <summary>
        /// 民生
        /// </summary>
        LIVELIHOOD = 4,
        /// <summary>
        /// 固定事件
        /// </summary>
        STATICEVENT = 5,
        /// <summary>
        /// 随机事件
        /// </summary>
        STOCHASTICEVENT = 6,
        /// <summary>
        /// 动物
        /// </summary>
        ANIMALS = 7,
        /// <summary>
        /// 交通事件
        /// </summary>
        TRAFFICEVENT = 8,
        /// <summary>
        /// 增减益卡
        /// </summary>
        BUFF = 9,
    }

} 

