
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class LocalizeForms : Luban.BeanBase
{
    public LocalizeForms(JSONNode _buf) 
    {
        { if(!_buf["localizeKey"].IsString) { throw new SerializationException(); }  LocalizeKey = _buf["localizeKey"]; }
        { if(!_buf["zh_cn"].IsString) { throw new SerializationException(); }  ZhCn = _buf["zh_cn"]; }
        { if(!_buf["zh_tw"].IsString) { throw new SerializationException(); }  ZhTw = _buf["zh_tw"]; }
        { if(!_buf["en_us"].IsString) { throw new SerializationException(); }  EnUs = _buf["en_us"]; }
    }

    public static LocalizeForms DeserializeLocalizeForms(JSONNode _buf)
    {
        return new LocalizeForms(_buf);
    }

    /// <summary>
    /// 本地化键值(自动生成)
    /// </summary>
    public readonly string LocalizeKey;
    /// <summary>
    /// 中文简体(需填写)
    /// </summary>
    public readonly string ZhCn;
    /// <summary>
    /// 中文繁体(需填写
    /// </summary>
    public readonly string ZhTw;
    /// <summary>
    /// 英文(需填写
    /// </summary>
    public readonly string EnUs;
   
    public const int __ID__ = 1468803974;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "localizeKey:" + LocalizeKey + ","
        + "zhCn:" + ZhCn + ","
        + "zhTw:" + ZhTw + ","
        + "enUs:" + EnUs + ","
        + "}";
    }
}

}
