
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public card.TbCardData TbCardData {get; }
    public localize.TbLocalizeTable TbLocalizeTable {get; }
    public card.TbFormula TbFormula {get; }
    public card.TbIcon TbIcon {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbCardData = new card.TbCardData(loader("card_tbcarddata"));
        TbLocalizeTable = new localize.TbLocalizeTable(loader("localize_tblocalizetable"));
        TbFormula = new card.TbFormula(loader("card_tbformula"));
        TbIcon = new card.TbIcon(loader("card_tbicon"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbCardData.ResolveRef(this);
        TbLocalizeTable.ResolveRef(this);
        TbFormula.ResolveRef(this);
        TbIcon.ResolveRef(this);
    }
}

}
